# Generated by Django 3.2.9 on 2021-11-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemInformasiKeuangan', '0008_auto_20211129_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('code_sof', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemInformasiKeuangan.sourceoffunds')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
